# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'SDKFrontiOS' do
	pod 'SwiftyJSON', "3.0.0"
	pod "youtube-ios-player-helper", "~> 0.1.4"
end
target 'SDKFrontiOSTests' do
    pod 'SwiftyJSON', "3.0.0"
    pod "youtube-ios-player-helper", "~> 0.1.4"
end
target 'SDKFrontiOSUITests' do
    pod 'SwiftyJSON', "3.0.0"
    pod "youtube-ios-player-helper", "~> 0.1.4"
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end