# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'SDKFrontiOS' do
pod 'SwiftyJSON'
end
target 'SDKFrontiOSTests' do
    pod 'SwiftyJSON'
end
target 'SDKFrontiOSUITests' do
    pod 'SwiftyJSON'
end
